services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ./binary:/binary
      - ./data:/app/data
    ports:
      - 5000:5000

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: vsc_db
      POSTGRES_USER: vsc_user
      POSTGRES_PASSWORD: vsc_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443